# Generated by Django 2.2.1 on 2020-03-07 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crosswords', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='word',
            options={'ordering': ['-id']},
        ),
        migrations.AddField(
            model_name='word',
            name='source',
            field=models.CharField(choices=[('O', 'Ozigov'), ('W', 'Wiki')], default='O', max_length=1),
        ),
    ]
