# Generated by Django 2.2.1 on 2020-03-07 14:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crosswords', '0002_auto_20200307_0950'),
        ('crosswords', '0002_auto_20190818_1932'),
    ]

    operations = [
    ]
